### ISSUE TITLE
seeing some warning messages during the ansible_galaxy_collection@v2 container build.

### ISSUE THREAD

**Issue by sabandi** [artis3n/ansible_galaxy_collection#135]
seeing some warning messages during the ansible_galaxy_collection@v2 container build.

![image](https://user-images.githubusercontent.com/33410431/117995636-1b868d80-b35f-11eb-95b8-e675b1912ca5.png)

The issue seems to be because of missing package.json file in the automated release of this action.

Can we explicitly remove the `RUN npm install --production` from the Dockerfile during the auto release phase as the repo already contains the compiled `dist/` directory.

The change would like below:

```
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
index b38c019..c848f09 100644
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -13,6 +13,7 @@ jobs:
         uses: technote-space/release-github-actions@v7.0.5
         with:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          BUILD_COMMAND: npm install && npm run build && sed -i '/RUN npm install --production/d' Dockerfile

   deploy:
     runs-on: ubuntu-latest
```

Please let me know if you want me to raise a PR for this issue

**Comment by artis3n** [comment]
The `dist/` doesn't include the necessary prod libraries hence the `--production` flag. But let me take a look at this and should fix the error in a PR soon

**Comment by artis3n** [comment]
I went ahead and bumped the node version from 14 to 16 in #136 and I'm not seeing this error occur during container build locally. I also don't see that error in the latest release via the GitHub Action workflow - https://github.com/artis3n/ansible_galaxy_collection/runs/2561915321?check_suite_focus=true .

Regardless, will push out a minor update for the node 16 container. Let me know if you see this error with that new version. If you do, please provide more information around the conditions that this occurs, preferably a link to your build if it is public.

**Comment by artis3n** [comment]
`2.3.0` is now released. Any future use on `v2` will automatically pick that up - let me know how it goes.

**Comment by sabandi** [comment]
Thanks for the fix @artis3n. It seems to be working now. 

Apologies for the delay.
