### ISSUE TITLE
npm ERR! Tracker "idealTree" already exists

### ISSUE THREAD

**Issue by ahmadalli** [artis3n/ansible_galaxy_collection#137]
Hi
I'm getting `npm ERR! Tracker "idealTree" already exists` error.
checkout [this job](https://github.com/ahmadalli/ansible/runs/2598046262?check_suite_focus=true) for more info

**Comment by artis3n** [comment]
Thanks for filing this - this is new behavior starting in node 15 and I jumped the container from 14 to 16 recently. I will follow [this](https://stackoverflow.com/a/65443098) to fix it shortly.

**Comment by artis3n** [comment]
`v2.4.0` was just released to resolve this, which auto-closed the ticket. The next run of this action on `@v2` will pick up the changes and you shouldn't see that error again.

**Comment by ahmadalli** [comment]
would you please check this job now? https://github.com/ahmadalli/ansible/runs/2607821650?check_suite_focus=true

**Comment by artis3n** [comment]
This is real weird. I swear this [runs through tests](https://github.com/artis3n/ansible_galaxy_collection/runs/2606934004?check_suite_focus=true#step:8:411) to make sure it works before releasing. I'll need to look into that error some more

**Comment by artis3n** [comment]
I cannot reproduce this on another action run. Honestly no idea what is happening there. I noticed this key distinction between the image built by this repo and the one built during your run invocation:

https://github.com/ahmadalli/ansible/runs/2607821650?check_suite_focus=true#step:2:384

```
   ---> 4e024e2681a8
  Step 9/10 : RUN npm install --production
   ---> Running in 0dbe43c357b0
  
  removed 12 packages, and audited 1 package in 710ms
```

https://github.com/artis3n/ansible_galaxy_collection/runs/2616356993?check_suite_focus=true#step:6:423

```
 #12 [7/7] RUN npm install --production
#12 sha256:0851491b363ea69e78699d5efffb38f99fc61e3c490a97dd765656cd3c86e094
#12 2.602 
#12 2.602 added 12 packages, and audited 13 packages in 2s
```

Why that happens when you call this action, I do not know. My recommendation is to use:

```yml
- uses: docker://ghcr.io/artis3n/ansible_galaxy_collection:v2.4.1
```

That will use the already built, published container produced by the deploy process in this repo that is built correctly.

**Comment by artis3n** [comment]
Let me know if that resolves the issue

**Comment by artis3n** [comment]
#141 was filed for this second issue as well. Given the issue title matches the error, I am going to use that issue to work on this error for any future folks that come to the repo. Will keep both of these tickets open until the issue is resolved.

**Comment by ahmadalli** [comment]
> Why that happens when you call this action, I do not know. My recommendation is to use:
> 
> ```yaml
> - uses: docker://ghcr.io/artis3n/ansible_galaxy_collection:v2.4.1
> ```
> 
> That will use the already built, published container produced by the deploy process in this repo that is built correctly.

I've tried it in https://github.com/ahmadalli/ansible/commit/bf51e1f93fa444cbc12c0c8682b7a130e50f6c88 but the job failed again: https://github.com/ahmadalli/ansible/runs/2628247704?check_suite_focus=true

**Comment by artis3n** [comment]
See #141 for more details but

```yml
- uses: docker://ghcr.io/artis3n/ansible_galaxy_collection:v2.4.2
```

will work without issue while I resolve the issue with the "regular" method of invoking the action.

**Comment by artis3n** [comment]
Ok this is fixed again for uses of `- uses: artis3n/ansible_galaxy_collection@v2` as well as of `v2.4.4`.
https://github.com/artis3n/test-ansible-collection/runs/2635896799?check_suite_focus=true
