### ISSUE TITLE
Error: Was unable to read the galaxy.yml file at path: galaxy.yml

### ISSUE THREAD

**Issue by pescobar** [artis3n/ansible_galaxy_collection#326]
I am testing this action in this repo https://github.com/scicore-unibas-ch/ansible-modules-guacamole , which has a `galaxy.yml` file in the root folder, but I still get the error `Error: Was unable to read the galaxy.yml file at path: galaxy.yml`

Is this a bug or am I missing anything?

**Comment by artis3n** [comment]
Hmm, let me fork your thing and see if I can tell what's going wrong

**Comment by artis3n** [comment]
Ah! Add `actions/checkout` as the first step before running the collection action :)

**Comment by artis3n** [comment]
Updated the README to provide a clearer example of the minimal usage: https://github.com/artis3n/ansible_galaxy_collection/pull/327

Let me know if that starts working for you!

**Comment by pescobar** [comment]
thanks for the quick answer. 

I can confirm that the suggested fix by adding `- uses: actions/checkout@v3` fixes the problem.

Now I get a different error but that one is something for me to fix so I am closing this issue as solved. Thanks again.

**Comment by artis3n** [comment]
FWIW you're using someone's forked version of this repo so there may be some errors introduced there. You can see if `artis3n/ansible_galaxy_collection@v2` works for you.

**Comment by pescobar** [comment]
thanks for the reminder. I was doing some testing and I forgot to change the collection version. 

Now I am using your collection and I fixed my CI config. Publish to galaxy works again :)
