### ISSUE TITLE
Allow templating of galaxy.yml file for version key

### ISSUE THREAD

**Issue by geerlingguy** [artis3n/ansible_galaxy_collection#49]
I've been working on publishing collections on git tags from GitHub automatically, and have it set up for some of my personal collections, but have had to hold of on doing it for other collections like `community.kubernetes` (see https://github.com/ansible-collections/kubernetes/issues/43) because the Galaxy token is global to my account, and anyone who could get some code into the Kubernetes collection could technically push to any project I have rights to in Galaxy.

However, in my personal collections, I also use a templated `galaxy.yml` file which lets me inject a version at build time (so I don't have to commit the version to GitHub, then tag it, then release it). Is there any way this action could support injecting a tag, e.g. when GitHub Actions runs, it grabs the tag (if it's a tag build), templates it into `galaxy.yml`, then runs the build and pushes the artifact?

**Comment by artis3n** [comment]
That's a great idea, I'll work on this over the weekend

**Comment by artis3n** [comment]
Made some significant refactors and completed #17 which puts me in a good place to get this done tomorrow. I'll link the PR to this issue. Will be validating semver-compliant input with https://github.com/npm/node-semver.

### galaxy_version

Semver-compatible string: `1` /  `1.1` / `1.1.1` /  `1.1.1-alpha`.

Dynamically inject a semver-compatible version into your `galaxy_config_file`.

**Comment by artis3n** [comment]
`v2.2.0` was released with a `galaxy_version` input parameter. Let me know if there's functionality you see still missing. I created #53 to add some additional functionality on top of this in the future.

**Comment by artis3n** [comment]
You should minimally use `v2.2.1` for this - see #55 where I encounter what seems to be a bug in GitHub Actions' runner's implementation of the default `WORKDIR` when building the image in a workflow run. The short summary is `v2.2.0` won't run but `v2.2.1` will.
