### ISSUE TITLE
Allow for separate build and publish calls

### ISSUE THREAD

**Issue by artis3n** [artis3n/ansible_galaxy_collection#56]
See https://github.com/ansible-collections/overview/pull/56#issuecomment-624592082 for further context:

> That action also mixes up two stages that are meant to be separate: build + publish. I'm strongly against promoting such an approach.
Ideally, it should be possible to test what's going to be published rather than just source. When build+publish are squashed there's a possibility that you'll be testing not exactly what the user will get. And this flow looks as follows:
> 
> test the src.
build a tarball + immediately publish it w/o testing that tarball.
What I advocate for is the following:
> 
> Build a tarball and store it as an artifact.
Have a test matrix that downloads that tarball, installs it and tests its contents (this is most likely a separate job or a collection of jobs).
Have a publish step that downloads the very same tarball that's been tested and uploads it to galaxy. This ensures that this step doesn't have a different build that's being tested.

The intention for this Action is to provide a painless way to publish a Collection to Galaxy, so the default will remain build + publish, however we will support a flag to build-only and publish-only from a local artifact.

**Comment by ericsysmin** [comment]
I like that enhancement :)

**Comment by artis3n** [comment]
Well, this is finally about to land :) See it in action [here](https://github.com/artis3n/ansible_galaxy_collection/runs/2652520968?check_suite_focus=true#step:3:454) and [here](https://github.com/artis3n/ansible_galaxy_collection/runs/2652520968?check_suite_focus=true#step:4:59).

@ericsysmin would be interested in your feedback on my approach in #148 . In particular, see the [changes in the README](https://github.com/artis3n/ansible_galaxy_collection/pull/148/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R62) for the new `build` and `publish` optional parameters and the implicit expectations I have for end users wishing to use these parameters. Is this what you had in mind?

Will keep open for about a week and merge next weekend.

The latest commit on the PR is `2eb4a1c841d4516be7bb541b4aaaa19df718ad08` so you can also test the behavior via:

```yml
- uses: artis3n/ansible_galaxy_collection@2eb4a1c841d4516be7bb541b4aaaa19df718ad08
```

with the parameters described in the README. Right now there isn't any feedback to confirm a user has disabled one of the options - I will probably add a standard log output saying something along the lines of `not building because build: false` to the action output for clarity.
