### ISSUE TITLE
Action cannot find galaxy.yml, but it exists

### ISSUE THREAD

**Issue by jhampson-dbre** [artis3n/ansible_galaxy_collection#60]
I'm attempting to add this action to a project, but it seems to be unable to find galaxy.yml.

```
Run artis3n/ansible_galaxy_collection@v2
  with:
    api_key: ***
    galaxy_version: v0.0.2
    galaxy_config_file: galaxy.yml
/usr/bin/docker run --name cc49567a1c911dfea64b8380238506c768c89f_b94aab --label cc4956 --workdir /github/workspace --rm -e INPUT_API_KEY -e INPUT_GALAXY_VERSION -e INPUT_COLLECTION_DIR -e INPUT_GALAXY_CONFIG_FILE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/home_assistant/home_assistant":"/github/workspace" cc4956:7a1c911dfea64b8380238506c768c89f
Error: ENOENT: no such file or directory, open 'galaxy.yml'
```

There is a `galaxy.yml` file in the [repository](https://github.com/jhampson-dbre/home_assistant/tree/main) root, so I'm not sure why it is saying it cannot find it.

**Comment by artis3n** [comment]
Can you link to the repo you are using this in or provide a snippet?

**Comment by artis3n** [comment]
I made a [small change](https://github.com/artis3n/ansible_galaxy_collection/pull/75/files#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dR67) in a PR, try using `artis3n@ansible_galaxy_collection@4e1cfce2c0742a9facc3ac20a30d43fddcb870c8` for the PR commit and see if you get a different result on your repo. I'll work on trying to reproduce that error.

**Comment by jhampson-dbre** [comment]
This was user-error. I had 2 jobs in the workflow, but only had the `checkout` action in the first job and not the second 🤦‍♂️. I added the checkout task and v2 of ansible_galaxy_collection successfully uploaded the collection to Galaxy.

There was one error message in the output:
```
/usr/local/lib/python3.5/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
  from cryptography.exceptions import InvalidSignature
```
But it seems to just be a warning at this point and not a terminating error.

Thanks for taking the time to look at this!

**Comment by artis3n** [comment]
That would do it!

The python cryptography error likely comes from whatever OS node:14-slim runs on and the version of python/Ansible available on that system. I'll make sure versions get pinned so we don't hit issues.
